<?php

use Illuminate\Database\Seeder;

class BackupMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-14 09:50:11',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:07:52',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-14 10:02:13',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:15',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 7,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:15',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 8,
                'created_at' => '2019-06-14 09:50:11',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 1,
                'created_at' => '2019-06-14 09:50:45',
                'updated_at' => '2019-06-14 10:01:16',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Sub Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-archive',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 2,
                'created_at' => '2019-06-14 09:51:08',
                'updated_at' => '2019-06-14 10:01:20',
                'route' => 'voyager.sub-categories.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-window-list',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 3,
                'created_at' => '2019-06-14 09:52:35',
                'updated_at' => '2019-06-14 10:01:22',
                'route' => 'voyager.types.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Colors',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paint-bucket',
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 4,
                'created_at' => '2019-06-14 09:53:32',
                'updated_at' => '2019-06-14 10:02:38',
                'route' => 'voyager.colors.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Sizes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paperclip',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 5,
                'created_at' => '2019-06-14 09:54:24',
                'updated_at' => '2019-06-14 10:01:26',
                'route' => 'voyager.sizes.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Quantities',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-barbell',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 7,
                'created_at' => '2019-06-14 09:55:07',
                'updated_at' => '2019-06-14 10:09:55',
                'route' => 'voyager.quantities.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Items',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 6,
                'created_at' => '2019-06-14 09:58:19',
                'updated_at' => '2019-06-14 10:09:55',
                'route' => 'voyager.items.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Mizo Bazarr',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-shop',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-06-14 10:01:03',
                'updated_at' => '2019-06-14 10:02:22',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Districts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 8,
                'created_at' => '2019-06-17 07:05:45',
                'updated_at' => '2019-06-17 07:08:15',
                'route' => 'voyager.districts.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Shipping Addresses',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 9,
                'created_at' => '2019-06-17 07:06:40',
                'updated_at' => '2019-06-17 07:08:19',
                'route' => 'voyager.shipping-addresses.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}